version: 2

builds:
  - main: ./cmd/paco/
    binary: paco
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: vianch
      name: homebrew-tap
    homepage: https://github.com/vianch/paco
    description: "TUI package.json script runner"
    license: "MIT"
    install: |
      bin.install "paco"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
